# Production.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: navrobotec

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: navrobotec
      app.kubernetes.io/instance: navrobotec-drone-prod

images:
  - name: ghcr.io/ragnar-vallhala/navrobotec-drone
    newTag: prod
