// Generated by scripts/make-focus-images.py — do not edit.
// The hash is the file's own content, so new artwork always lands on
// a new URL. Next serves optimised images `immutable`.
export const FOCUS_IMAGES = {
  "focus-layout": "/images/focus-layout.b79ecd21.webp",
  "focus-board": "/images/focus-board.a56ffb71.webp",
  "focus-vayu": "/images/focus-vayu.e0b00b50.webp",
} as const;
