// Generated by scripts/make-focus-images.py — do not edit.
// The hash is the file's own content, so new artwork always lands on
// a new URL. Next serves optimised images `immutable`.
export const FOCUS_IMAGES = {
  "focus-layout": "/images/focus-layout.b79ecd21.webp",
  "focus-timing": "/images/focus-timing.eae0188f.webp",
  "focus-scale": "/images/focus-scale.46fccd54.webp",
} as const;
