// Generated by scripts/make-page-images.py — do not edit.
// The hash is the file's own content, so new artwork always lands on
// a new URL. Next serves optimised images `immutable`.
export const PAGE_IMAGES = {
  "focus-layout": "/images/focus-layout.b79ecd21.webp",
  "focus-timing": "/images/focus-timing.eae0188f.webp",
  "focus-scale": "/images/focus-scale.46fccd54.webp",
  "hero-technology": "/images/hero-technology.c52c4574.webp",
} as const;
